"use client"
import { useState } from "react"
import { useRouter } from "next/navigation"
import { motion } from "framer-motion"
import {
  ArrowLeft,
  Save,
  Sparkles,
  Image,
  FileText,
  Calendar,
  Clock,
} from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Select } from "@/components/ui/select"
import { Badge } from "@/components/ui/badge"
import { useToast } from "@/components/ui/toast"
import { FadeIn } from "@/components/engagement/motion"

export default function NewContentPage() {
  const router = useRouter()
  const { addToast } = useToast()
  const [saving, setSaving] = useState(false)
  const [generating, setGenerating] = useState(false)
  const [form, setForm] = useState({
    title: "",
    body: "",
    platform: "",
    type: "text" as "text" | "image" | "video" | "carousel",
    scheduledDate: "",
    scheduledTime: "",
    hashtags: "",
    tone: "professional",
  })

  const handleAIGenerate = async () => {
    if (!form.title) {
      addToast("Enter a topic first", "warning")
      return
    }
    setGenerating(true)
    try {
      await new Promise(resolve => setTimeout(resolve, 2000))
      setForm(p => ({
        ...p,
        body: `Here's an engaging post about ${form.title}:\n\nDiscover the key insights that are transforming the landscape. From innovative strategies to actionable tips, this is what you need to know.\n\nWhat are your thoughts? Share below!`,
      }))
      addToast("Content generated by AI", "success")
    } catch {
      addToast("AI generation failed", "error")
    } finally {
      setGenerating(false)
    }
  }

  const handleSave = async () => {
    if (!form.title || !form.body) {
      addToast("Title and content are required", "error")
      return
    }
    setSaving(true)
    try {
      await new Promise(resolve => setTimeout(resolve, 1000))
      addToast("Content created successfully", "success")
      router.push("/content")
    } catch {
      addToast("Failed to create content", "error")
    } finally {
      setSaving(false)
    }
  }

  const handleSchedule = async () => {
    if (!form.scheduledDate || !form.scheduledTime) {
      addToast("Select a date and time to schedule", "error")
      return
    }
    setSaving(true)
    try {
      await new Promise(resolve => setTimeout(resolve, 1000))
      addToast(`Content scheduled for ${form.scheduledDate} at ${form.scheduledTime}`, "success")
      router.push("/content")
    } catch {
      addToast("Failed to schedule content", "error")
    } finally {
      setSaving(false)
    }
  }

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center gap-4">
        <Button variant="ghost" size="icon" onClick={() => router.back()} aria-label="Go back">
          <ArrowLeft className="h-5 w-5" />
        </Button>
        <div>
          <h1
            className="text-2xl font-bold"
            style={{ fontFamily: "var(--font-plus-jakarta)", color: "var(--text-primary)" }}
          >
            Create Content
          </h1>
          <p className="text-sm mt-0.5" style={{ color: "var(--text-secondary)" }}>
            Create and schedule engaging content with AI assistance
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Main Editor */}
        <div className="lg:col-span-2 space-y-4">
          <FadeIn>
            <Card>
              <CardHeader>
                <CardTitle>Content</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <label htmlFor="title" className="block text-sm font-medium mb-1.5" style={{ color: "var(--text-primary)" }}>
                    Title
                  </label>
                  <Input
                    id="title"
                    placeholder="What's your content about?"
                    value={form.title}
                    onChange={e => setForm(p => ({ ...p, title: e.target.value }))}
                  />
                </div>
                <div>
                  <div className="flex items-center justify-between mb-1.5">
                    <label htmlFor="body" className="text-sm font-medium" style={{ color: "var(--text-primary)" }}>
                      Content
                    </label>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={handleAIGenerate}
                      disabled={generating}
                    >
                      <Sparkles className="h-3.5 w-3.5 mr-1.5" style={{ color: "var(--accent)" }} />
                      {generating ? "Generating..." : "AI Generate"}
                    </Button>
                  </div>
                  <Textarea
                    id="body"
                    rows={8}
                    placeholder="Write your content here or use AI to generate it..."
                    value={form.body}
                    onChange={e => setForm(p => ({ ...p, body: e.target.value }))}
                  />
                  <div className="flex justify-between mt-1.5">
                    <p className="text-xs" style={{ color: "var(--text-muted)" }}>
                      {form.body.length} characters
                    </p>
                    <p className="text-xs" style={{ color: "var(--text-muted)" }}>
                      ~{Math.ceil(form.body.split(/\s+/).length / 2)} min read
                    </p>
                  </div>
                </div>
                <div>
                  <label htmlFor="hashtags" className="block text-sm font-medium mb-1.5" style={{ color: "var(--text-primary)" }}>
                    Hashtags
                  </label>
                  <Input
                    id="hashtags"
                    placeholder="#socialmedia #marketing #growth"
                    value={form.hashtags}
                    onChange={e => setForm(p => ({ ...p, hashtags: e.target.value }))}
                  />
                </div>
              </CardContent>
            </Card>
          </FadeIn>

          {/* Media */}
          <FadeIn delay={0.1}>
            <Card>
              <CardHeader>
                <CardTitle>Media</CardTitle>
                <CardDescription>Add images, videos, or create a carousel</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="border-2 border-dashed rounded-xl p-8 text-center" style={{ borderColor: "var(--border-default)" }}>
                  <Image className="h-8 w-8 mx-auto mb-3" style={{ color: "var(--text-muted)" }} />
                  <p className="text-sm font-medium mb-1" style={{ color: "var(--text-primary)" }}>
                    Drag & drop files here
                  </p>
                  <p className="text-xs mb-3" style={{ color: "var(--text-muted)" }}>
                    PNG, JPG, GIF, MP4 up to 50MB
                  </p>
                  <Button variant="secondary" size="sm">Browse files</Button>
                </div>
              </CardContent>
            </Card>
          </FadeIn>
        </div>

        {/* Sidebar */}
        <div className="space-y-4">
          <FadeIn delay={0.1}>
            <Card>
              <CardHeader>
                <CardTitle>Settings</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <label className="block text-sm font-medium mb-1.5" style={{ color: "var(--text-primary)" }}>
                    Platform
                  </label>
                  <Select
                    options={[
                      { value: "Instagram", label: "Instagram" },
                      { value: "Twitter", label: "Twitter" },
                      { value: "LinkedIn", label: "LinkedIn" },
                      { value: "TikTok", label: "TikTok" },
                      { value: "Facebook", label: "Facebook" },
                    ]}
                    value={form.platform}
                    onValueChange={v => setForm(p => ({ ...p, platform: v }))}
                    placeholder="Select platform"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium mb-1.5" style={{ color: "var(--text-primary)" }}>
                    Content type
                  </label>
                  <div className="flex flex-wrap gap-2">
                    {(["text", "image", "video", "carousel"] as const).map(type => (
                      <button
                        key={type}
                        onClick={() => setForm(p => ({ ...p, type }))}
                        className="inline-flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-medium transition-colors border"
                        style={{
                          borderColor: form.type === type ? "var(--accent)" : "var(--border-default)",
                          backgroundColor: form.type === type ? "color-mix(in srgb, var(--accent) 10%, transparent)" : "var(--bg-secondary)",
                          color: form.type === type ? "var(--accent)" : "var(--text-secondary)",
                        }}
                      >
                        {type === "text" && <FileText className="h-3 w-3" />}
                        {type === "image" && <Image className="h-3 w-3" />}
                        {type === "video" && "🎬"}
                        {type === "carousel" && "📑"}
                        {type}
                      </button>
                    ))}
                  </div>
                </div>
                <div>
                  <label className="block text-sm font-medium mb-1.5" style={{ color: "var(--text-primary)" }}>
                    Tone
                  </label>
                  <Select
                    options={[
                      { value: "professional", label: "Professional" },
                      { value: "casual", label: "Casual" },
                      { value: "humorous", label: "Humorous" },
                      { value: "inspirational", label: "Inspirational" },
                    ]}
                    value={form.tone}
                    onValueChange={v => setForm(p => ({ ...p, tone: v }))}
                  />
                </div>
              </CardContent>
            </Card>
          </FadeIn>

          <FadeIn delay={0.2}>
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Calendar className="h-4 w-4" style={{ color: "var(--accent)" }} />
                  Schedule
                </CardTitle>
                <CardDescription>Set when to publish</CardDescription>
              </CardHeader>
              <CardContent className="space-y-3">
                <div>
                  <label htmlFor="schedDate" className="block text-sm font-medium mb-1.5" style={{ color: "var(--text-primary)" }}>
                    Date
                  </label>
                  <Input
                    id="schedDate"
                    type="date"
                    value={form.scheduledDate}
                    onChange={e => setForm(p => ({ ...p, scheduledDate: e.target.value }))}
                  />
                </div>
                <div>
                  <label htmlFor="schedTime" className="block text-sm font-medium mb-1.5" style={{ color: "var(--text-primary)" }}>
                    Time
                  </label>
                  <Input
                    id="schedTime"
                    type="time"
                    value={form.scheduledTime}
                    onChange={e => setForm(p => ({ ...p, scheduledTime: e.target.value }))}
                  />
                </div>
              </CardContent>
            </Card>
          </FadeIn>

          {/* Actions */}
          <div className="flex flex-col gap-2">
            <Button onClick={handleSchedule} disabled={saving} className="w-full">
              {saving ? (
                <span className="flex items-center gap-2">
                  <span className="h-4 w-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                  Saving...
                </span>
              ) : (
                <span className="flex items-center gap-2">
                  <Clock className="h-4 w-4" />
                  Schedule
                </span>
              )}
            </Button>
            <Button variant="secondary" onClick={handleSave} disabled={saving} className="w-full">
              <Save className="h-4 w-4 mr-1.5" />
              Save as draft
            </Button>
          </div>
        </div>
      </div>
    </div>
  )
}
